name: py39

channels:
  - conda-forge

dependencies:
  - python==3.9.*
  - pytest==7.2.*
  - pytest-cov==4.0.*
  - black==20.*
  - flake8==3.9.*
  - pre-commit==2.10.*
  - seaborn
  - matplotlib
  - numpy
  - pandas
